------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                    I_PRODUCT_NAME|                                           I_BRAND|                                           I_CLASS|                                        I_CATEGORY|                                     QOH|
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|ationbarn station                                 |                                              null|                                              null|                                              null|                              430.357724|
|ationbarn station                                 |amalgbrand #8                                     |                                              null|                                              null|                              430.357724|
|ationbarn station                                 |amalgbrand #8                                     |bathroom                                          |                                              null|                              430.357724|
|ationbarn station                                 |amalgbrand #8                                     |bathroom                                          |Home                                              |                              430.357724|
|ationoughtn stn st                                |                                              null|                                              null|                                              null|                              435.265060|
|ationoughtn stn st                                |edu packimporto #2                                |                                              null|                                              null|                              435.265060|
|ationoughtn stn st                                |edu packimporto #2                                |sports-apparel                                    |                                              null|                              435.265060|
|ationoughtn stn st                                |edu packimporto #2                                |sports-apparel                                    |Men                                               |                              435.265060|
|ationationprin st                                 |                                              null|                                              null|                                              null|                              435.510288|
|ationationprin st                                 |amalgexporti #2                                   |                                              null|                                              null|                              435.510288|
|ationationprin st                                 |amalgexporti #2                                   |newborn                                           |                                              null|                              435.510288|
|ationationprin st                                 |amalgexporti #2                                   |newborn                                           |Children                                          |                              435.510288|
|oughtcallyn stantiought                           |                                              null|                                              null|                                              null|                              436.494024|
|oughtcallyn stantiought                           |corpcorp #2                                       |                                              null|                                              null|                              436.494024|
|oughtcallyn stantiought                           |corpcorp #2                                       |rings                                             |                                              null|                              436.494024|
|oughtcallyn stantiought                           |corpcorp #2                                       |rings                                             |Jewelry                                           |                              436.494024|
|callyesebaration                                  |                                              null|                                              null|                                              null|                              437.394309|
|callyesebaration                                  |namelesscorp #7                                   |                                              null|                                              null|                              437.394309|
|callyesebaration                                  |namelesscorp #7                                   |mens watch                                        |                                              null|                              437.394309|
|callyesebaration                                  |namelesscorp #7                                   |mens watch                                        |Jewelry                                           |                              437.394309|
|n stprieingationought                             |                                              null|                                              null|                                              null|                              439.064777|
|n stprieingationought                             |namelesscorp #8                                   |                                              null|                                              null|                              439.064777|
|n stprieingationought                             |namelesscorp #8                                   |mens watch                                        |                                              null|                              439.064777|
|n stprieingationought                             |namelesscorp #8                                   |mens watch                                        |Jewelry                                           |                              439.064777|
|priationn stn st                                  |                                              null|                                              null|                                              null|                              439.096000|
|priationn stn st                                  |importoscholar #2                                 |                                              null|                                              null|                              439.096000|
|priationn stn st                                  |importoscholar #2                                 |country                                           |                                              null|                              439.096000|
|priationn stn st                                  |importoscholar #2                                 |country                                           |Music                                             |                              439.096000|
|n stcallyableoughtought                           |                                              null|                                              null|                                              null|                              439.718367|
|n stcallyableoughtought                           |amalgimporto #2                                   |                                              null|                                              null|                              439.718367|
|n stcallyableoughtought                           |amalgimporto #2                                   |accessories                                       |                                              null|                              439.718367|
|n stcallyableoughtought                           |amalgimporto #2                                   |accessories                                       |Men                                               |                              439.718367|
|n stbarought                                      |                                              null|                                              null|                                              null|                              440.314741|
|n stbarought                                      |corpbrand #10                                     |                                              null|                                              null|                              440.314741|
|n stbarought                                      |corpbrand #10                                     |rugs                                              |                                              null|                              440.314741|
|n stbarought                                      |corpbrand #10                                     |rugs                                              |Home                                              |                              440.314741|
|n stn stantioughtought                            |                                              null|                                              null|                                              null|                              440.928571|
|n stn stantioughtought                            |exportimaxi #8                                    |                                              null|                                              null|                              440.928571|
|n stn stantioughtought                            |exportimaxi #8                                    |computers                                         |                                              null|                              440.928571|
|n stn stantioughtought                            |exportimaxi #8                                    |computers                                         |Books                                             |                              440.928571|
|n stcallyesepriought                              |                                              null|                                              null|                                              null|                              441.541833|
|n stcallyesepriought                              |edu packscholar #2                                |                                              null|                                              null|                              441.541833|
|n stcallyesepriought                              |edu packscholar #2                                |classical                                         |                                              null|                              441.541833|
|n stcallyesepriought                              |edu packscholar #2                                |classical                                         |Music                                             |                              441.541833|
|priantiationation                                 |                                              null|                                              null|                                              null|                              441.670732|
|priantiationation                                 |importoimporto #2                                 |                                              null|                                              null|                              441.670732|
|priantiationation                                 |importoimporto #2                                 |shirts                                            |                                              null|                              441.670732|
|priantiationation                                 |importoimporto #2                                 |shirts                                            |Men                                               |                              441.670732|
|oughtbarantiese                                   |                                              null|                                              null|                                              null|                              441.745968|
|oughtbarantiese                                   |exportiedu pack #2                                |                                              null|                                              null|                              441.745968|
|oughtbarantiese                                   |exportiedu pack #2                                |kids                                              |                                              null|                              441.745968|
|oughtbarantiese                                   |exportiedu pack #2                                |kids                                              |Shoes                                             |                              441.745968|
|oughtbarprin st                                   |                                              null|                                              null|                                              null|                              442.073469|
|oughtbarprin st                                   |edu packscholar #2                                |                                              null|                                              null|                              442.073469|
|oughtbarprin st                                   |edu packscholar #2                                |classical                                         |                                              null|                              442.073469|
|oughtbarprin st                                   |edu packscholar #2                                |classical                                         |Music                                             |                              442.073469|
|ationeingation                                    |                                              null|                                              null|                                              null|                              443.782258|
|ationeingation                                    |amalgexporti #2                                   |                                              null|                                              null|                              443.782258|
|ationeingation                                    |amalgexporti #2                                   |newborn                                           |                                              null|                              443.782258|
|ationeingation                                    |amalgexporti #2                                   |newborn                                           |Children                                          |                              443.782258|
|ationbarn stableought                             |                                              null|                                              null|                                              null|                              444.092742|
|ationbarn stableought                             |corpbrand #8                                      |                                              null|                                              null|                              444.092742|
|ationbarn stableought                             |corpbrand #8                                      |rugs                                              |                                              null|                              444.092742|
|ationbarn stableought                             |corpbrand #8                                      |rugs                                              |Home                                              |                              444.092742|
|eseationcallyableought                            |                                              null|                                              null|                                              null|                              444.544355|
|eseationcallyableought                            |importoexporti #1                                 |                                              null|                                              null|                              444.544355|
|eseationcallyableought                            |importoexporti #1                                 |infants                                           |                                              null|                              444.544355|
|eseationcallyableought                            |importoexporti #1                                 |infants                                           |Children                                          |                              444.544355|
|eingableableationought                            |                                              null|                                              null|                                              null|                              444.714286|
|eingableableationought                            |amalgimporto #1                                   |                                              null|                                              null|                              444.714286|
|eingableableationought                            |amalgimporto #1                                   |accessories                                       |                                              null|                              444.714286|
|eingableableationought                            |amalgimporto #1                                   |accessories                                       |Men                                               |                              444.714286|
|n steseantiation                                  |                                              null|                                              null|                                              null|                              445.331967|
|n steseantiation                                  |univmaxi #10                                      |                                              null|                                              null|                              445.331967|
|n steseantiation                                  |univmaxi #10                                      |pools                                             |                                              null|                              445.331967|
|n steseantiation                                  |univmaxi #10                                      |pools                                             |Sports                                            |                              445.331967|
|antibareingantiought                              |                                              null|                                              null|                                              null|                              445.406504|
|antibareingantiought                              |importoimporto #2                                 |                                              null|                                              null|                              445.406504|
|antibareingantiought                              |importoimporto #2                                 |shirts                                            |                                              null|                              445.406504|
|antibareingantiought                              |importoimporto #2                                 |shirts                                            |Men                                               |                              445.406504|
|ationantibarationought                            |                                              null|                                              null|                                              null|                              445.419087|
|ationantibarationought                            |univmaxi #8                                       |                                              null|                                              null|                              445.419087|
|ationantibarationought                            |univmaxi #8                                       |pools                                             |                                              null|                              445.419087|
|ationantibarationought                            |univmaxi #8                                       |pools                                             |Sports                                            |                              445.419087|
|oughtpricallybarought                             |                                              null|                                              null|                                              null|                              445.485944|
|oughtpricallybarought                             |edu packexporti #2                                |                                              null|                                              null|                              445.485944|
|oughtpricallybarought                             |edu packexporti #2                                |school-uniforms                                   |                                              null|                              445.485944|
|oughtpricallybarought                             |edu packexporti #2                                |school-uniforms                                   |Children                                          |                              445.485944|
|ableationprieing                                  |                                              null|                                              null|                                              null|                              445.995833|
|ableationprieing                                  |amalgamalg #1                                     |                                              null|                                              null|                              445.995833|
|ableationprieing                                  |amalgamalg #1                                     |dresses                                           |                                              null|                              445.995833|
|ableationprieing                                  |amalgamalg #1                                     |dresses                                           |Women                                             |                              445.995833|
|pribarpribarought                                 |                                              null|                                              null|                                              null|                              446.040816|
|pribarpribarought                                 |edu packimporto #2                                |                                              null|                                              null|                              446.040816|
|pribarpribarought                                 |edu packimporto #2                                |sports-apparel                                    |                                              null|                              446.040816|
|pribarpribarought                                 |edu packimporto #2                                |sports-apparel                                    |Men                                               |                              446.040816|
|oughtn stprin st                                  |                                              null|                                              null|                                              null|                              447.266667|
|oughtn stprin st                                  |exportiamalgamalg #8                              |                                              null|                                              null|                              447.266667|
|oughtn stprin st                                  |exportiamalgamalg #8                              |stereo                                            |                                              null|                              447.266667|
|oughtn stprin st                                  |exportiamalgamalg #8                              |stereo                                            |Electronics                                       |                              447.266667|
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
